### ISSUE TITLE
Interdependenzen bei neuem Plan

### ISSUE THREAD

**Issue by rlucke** [virtUOS/studip-unterrichtsplanung#1]
Wird ein Plan erstellt müssen die Interdependenzen abrufbar sein. Egal ob etwas in der DB steht oder nicht.

**Comment by tgloeggl** [comment]
Das ist schwierig zu implementieren, es gibt keine Datenstruktur, in welcher definiert ist, welche Interdependenzen es überhaupt gibt. Die Aufzählung der Interdependenzen existiert bisher nur auf der Oberfläche.
Gibt es für die angefragte Struktur im angefragten Plan keine Daten, so wird allerdings kein Fehler geworfen und es wird eine leere Datenstruktur zurückgegeben.
Entweder das passt so oder man ersetzt die leer Datenstruktur durch eine vordefiniert. Die vordefiniert bräuchte ich dann allerdings einmal.
