### ISSUE TITLE
api für du_schedules

### ISSUE THREAD

**Issue by rlucke** [virtUOS/studip-unterrichtsplanung#10]
Um einen Verlaufplan anzulegen und zu speichern werden routes benötigt. Da pro Plan nur ein Verlaufsplan existiert lässt sich dieser über die PlanId ermitteln.
./api/schedules/plans_id als put und post

**Comment by tgloeggl** [comment]
Die Route lautet **/plans/{id}/schedules**, um die Verlaufspläne zu erhalten.
Unter **/schedules** finden sich die üblichen Routen zum erstelln, aktualisieren und löschen.

So ist es technisch möglich, mehrere Verlaufspläne pro Plan zu haben, man muss dieses ja nicht ausschöpfen.
 
Passt das auch?

**Comment by rlucke** [comment]
Ja das passt, aber es soll nur einen Verlaufsplan pro Plan geben
