### ISSUE TITLE
PDF Export

### ISSUE THREAD

**Issue by rlucke** [virtUOS/studip-unterrichtsplanung#11]
Ein Plan soll als PDF exportiert werden können. Hierzu müssen alle Summary Felder, die Metadaten und der Verlaufsplan in ein PDF Dokument geschrieben werden.

**Comment by tgloeggl** [comment]
https://github.com/virtUOS/studip-unterrichtsplanung/commit/ff84d2ef1e6137b072cbd62a81fe1f28d33e6331

Verlaufsplan fehlt noch

**Comment by tgloeggl** [comment]
https://github.com/virtUOS/studip-unterrichtsplanung/commit/becc8658b1d2c3cb2cdb7a5eafdaddfab011bff8

**Comment by tgloeggl** [comment]
Was ist mit den Metadaten? Gibt es da irgendetwas, das mit exportiert werden muss?
