### ISSUE TITLE
Word Export

### ISSUE THREAD

**Issue by rlucke** [virtUOS/studip-unterrichtsplanung#12]
Ein Plan soll als Word exportiert werden können. Hierzu müssen alle Summary Felder, die Metadaten und der Verlaufsplan in ein Word Dokument geschrieben werden.

**Comment by tgloeggl** [comment]
https://github.com/virtUOS/studip-unterrichtsplanung/commit/8b5d0bc7ef4665745fbabbd02ece4f3d96c68db3

Verlausplan fehlt noch.
