### ISSUE TITLE
structure ids für Infotexte die keine structure id haben

### ISSUE THREAD

**Issue by rlucke** [virtUOS/studip-unterrichtsplanung#14]
Infotexte für Übersichtsseiten, Verlaufsplan etc. brauchen besondere structure_ids, da diese Seiten keine Strukturelemente sind und daher auch keine entsprechende id haben.

**Comment by rlucke** [comment]
1000 für home
1001 für overview
1002 für editplan
1003 für editschedule
etc

**Comment by tgloeggl** [comment]
Wie wäre es mit -1, -2, etc.? So ist sichergestellt, dass es niemals Kollisionen mit "echten" Structure-Ids gibt.

**Comment by tgloeggl** [comment]
Die IDs kannst du auf jeden Fall frei wählen, einfach der infotext-Route hinposten und fertig, bzw. wir schreiben eine Migration, welche die Text in die DB schreibt.

**Comment by rlucke** [comment]
Eine Migration wäre gut um den ersten Schwung von Texten abzulegen. Dann müsste ich noch eine Admin-Oberfläche bauen um die Infotexte zu verwalten

**Comment by rlucke** [comment]
Sobald Infotexte vorhanden sind wird eine entsprechende Migration erstellt.
