### ISSUE TITLE
Export Mac

### ISSUE THREAD

**Issue by SKueth** [virtUOS/studip-unterrichtsplanung#36]
Könntet Ihr bitte Folgendes nochmal kontrollieren? (Wir konnten den Fehler selbst nicht reproduzieren.)
-	 „Konvertierung auf Word (Mac) fehlerhaft; Probleme beim Umformen in ein Word-Dokument“

**Comment by tgloeggl** [comment]
fixed in https://github.com/virtUOS/studip-unterrichtsplanung/commit/71532ef1baaa27cf820f488bb43cea9a4d882ae2
