### ISSUE TITLE
chdate für plans

### ISSUE THREAD

**Issue by rlucke** [virtUOS/studip-unterrichtsplanung#8]
Bei jeder Änderung an einem Plan, egal in welchem Bereich muss das chdate für den Plan neu gesetzt werden.

**Comment by tgloeggl** [comment]
Hmm, wenn ich das richtig sehe betrifft das die Routen _textfields_ und __summary__. Soll die Aktualisierung auch stattfinden, wenn etwas an __interdeps__ geändert wurde?

**Comment by rlucke** [comment]
Ja bei jeder Änderung. Auch wenn sich der Verlaufsplan ändert
